<a href="https://colab.research.google.com/github/codestashes/tflearn/blob/main/TensorTypes.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import tensorflow as tf

In [3]:
print(tf.__version__)

2.7.0


In [4]:
scalar = tf.constant(6)
type(scalar)

tensorflow.python.framework.ops.EagerTensor

In [5]:
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=6>

In [6]:
scalar.ndim

0

In [7]:
vec = tf.constant([10, 10])
vec

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [8]:
vec.ndim

1

In [9]:
mat = tf.constant([[1, 2], [3,4]])
mat

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4]], dtype=int32)>

In [10]:
mat.ndim

2

In [11]:
mat1 = tf.constant([[5, 6], [7, 8]], dtype=tf.int16)
print(mat1)
mat1.ndim

tf.Tensor(
[[5 6]
 [7 8]], shape=(2, 2), dtype=int16)


2

In [12]:
tensor1 = tf.constant([[[1, 2], [3, 4], [5, 6],
                        [11, 12], [13, 14], [15, 16]],
                       [[101, 102], [103, 104], [105, 106],
                        [111, 112], [113, 114], [115, 116]],
                       [[12, 22], [32, 42], [52, 62],
                        [112, 122], [132, 142], [152, 162]],
                       [[1001, 1002], [1003, 1004], [1005, 1006],
                        [1011, 1012], [1013, 1014], [1015, 1016]],
                       [[1, 2], [3, 4], [5, 6],
                        [11, 12], [13, 14], [15, 16]],
                       [[101, 102], [103, 104], [105, 106],
                        [111, 112], [113, 114], [115, 116]],
                       [[12, 22], [32, 42], [52, 62],
                        [112, 122], [132, 142], [152, 162]],
                       [[1001, 1002], [1003, 1004], [1005, 1006],
                        [1011, 1012], [1013, 1014], [1015, 1016]]])
tensor1.ndim

3

In [13]:
tensor1

<tf.Tensor: shape=(8, 6, 2), dtype=int32, numpy=
array([[[   1,    2],
        [   3,    4],
        [   5,    6],
        [  11,   12],
        [  13,   14],
        [  15,   16]],

       [[ 101,  102],
        [ 103,  104],
        [ 105,  106],
        [ 111,  112],
        [ 113,  114],
        [ 115,  116]],

       [[  12,   22],
        [  32,   42],
        [  52,   62],
        [ 112,  122],
        [ 132,  142],
        [ 152,  162]],

       [[1001, 1002],
        [1003, 1004],
        [1005, 1006],
        [1011, 1012],
        [1013, 1014],
        [1015, 1016]],

       [[   1,    2],
        [   3,    4],
        [   5,    6],
        [  11,   12],
        [  13,   14],
        [  15,   16]],

       [[ 101,  102],
        [ 103,  104],
        [ 105,  106],
        [ 111,  112],
        [ 113,  114],
        [ 115,  116]],

       [[  12,   22],
        [  32,   42],
        [  52,   62],
        [ 112,  122],
        [ 132,  142],
        [ 152,  162]],

       [[1001

In [14]:
var_tensor = tf.Variable([1, 2])

In [15]:
var_tensor

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([1, 2], dtype=int32)>

In [16]:
var_tensor[0].assign(25)
var_tensor

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([25,  2], dtype=int32)>

In [17]:
rand_t = tf.random.Generator.from_seed(42)

In [18]:
rand_t

In [19]:
rand_t1 = rand_t.normal(shape=(3, 6))
rand_t1

<tf.Tensor: shape=(3, 6), dtype=float32, numpy=
array([[-0.7565803 , -0.06854702,  0.07595026, -1.2573844 , -0.23193763,
        -1.8107855 ],
       [ 0.09988727, -0.50998646, -0.7535805 , -0.57166284,  0.1480774 ,
        -0.23362993],
       [-0.3522796 ,  0.40621263, -1.0523509 ,  1.2054597 ,  1.6874489 ,
        -0.4462975 ]], dtype=float32)>

In [20]:
uni_rand_t = tf.random.uniform(shape=(6, 2))
uni_rand_t

<tf.Tensor: shape=(6, 2), dtype=float32, numpy=
array([[0.50988424, 0.6940812 ],
       [0.26808643, 0.08117712],
       [0.24004161, 0.4085058 ],
       [0.83584964, 0.96037114],
       [0.2708038 , 0.7918148 ],
       [0.8817524 , 0.05122364]], dtype=float32)>

In [21]:
rand_t2 = rand_t.normal(shape=(3, 6))
rand_t2

<tf.Tensor: shape=(3, 6), dtype=float32, numpy=
array([[-0.50029814,  0.87708676, -0.60948575, -0.8924083 ,  0.31198648,
         2.377529  ],
       [-0.57386935, -0.52125114, -1.6117936 , -0.03135132,  1.3322345 ,
        -1.3204538 ],
       [-1.486233  ,  0.9383624 , -0.53740156,  0.6767252 ,  0.10983319,
        -2.8096533 ]], dtype=float32)>

In [22]:
rand_t1, rand_t2, rand_t1 == rand_t2

(<tf.Tensor: shape=(3, 6), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702,  0.07595026, -1.2573844 , -0.23193763,
         -1.8107855 ],
        [ 0.09988727, -0.50998646, -0.7535805 , -0.57166284,  0.1480774 ,
         -0.23362993],
        [-0.3522796 ,  0.40621263, -1.0523509 ,  1.2054597 ,  1.6874489 ,
         -0.4462975 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 6), dtype=float32, numpy=
 array([[-0.50029814,  0.87708676, -0.60948575, -0.8924083 ,  0.31198648,
          2.377529  ],
        [-0.57386935, -0.52125114, -1.6117936 , -0.03135132,  1.3322345 ,
         -1.3204538 ],
        [-1.486233  ,  0.9383624 , -0.53740156,  0.6767252 ,  0.10983319,
         -2.8096533 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 6), dtype=bool, numpy=
 array([[False, False, False, False, False, False],
        [False, False, False, False, False, False],
        [False, False, False, False, False, False]])>)

In [23]:
not_shuffled = tf.constant([[1, 2], [3, 4], [5,6]])
not_shuffled

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4],
       [5, 6]], dtype=int32)>

In [24]:
tf.random.shuffle(not_shuffled, seed=2)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4],
       [5, 6]], dtype=int32)>

In [25]:
tf.random.set_seed(2)
tf.random.shuffle(not_shuffled)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[5, 6],
       [3, 4],
       [1, 2]], dtype=int32)>

In [26]:
tf.ones([2, 5], dtype=tf.int16)

<tf.Tensor: shape=(2, 5), dtype=int16, numpy=
array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]], dtype=int16)>

In [27]:
tf.zeros([5, 1])

<tf.Tensor: shape=(5, 1), dtype=float32, numpy=
array([[0.],
       [0.],
       [0.],
       [0.],
       [0.]], dtype=float32)>

In [28]:
tf.ones(shape=(2, 3))

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[1., 1., 1.],
       [1., 1., 1.]], dtype=float32)>

In [29]:
import numpy as np
np_arr = np.arange(1, 25)
np_arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24])

In [30]:
A = tf.constant(np_arr)
A

<tf.Tensor: shape=(24,), dtype=int64, numpy=
array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24])>

In [31]:
B = tf.constant(np_arr, shape=(3, 2, 4))
B

<tf.Tensor: shape=(3, 2, 4), dtype=int64, numpy=
array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8]],

       [[ 9, 10, 11, 12],
        [13, 14, 15, 16]],

       [[17, 18, 19, 20],
        [21, 22, 23, 24]]])>

In [32]:
C = tf.constant(np_arr, shape=(6, 4))
C

<tf.Tensor: shape=(6, 4), dtype=int64, numpy=
array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20],
       [21, 22, 23, 24]])>

In [33]:
C.ndim

2

In [34]:
tf.size(B)

<tf.Tensor: shape=(), dtype=int32, numpy=24>

In [35]:
B[2, 0]

<tf.Tensor: shape=(4,), dtype=int64, numpy=array([17, 18, 19, 20])>

In [36]:
A.shape, B.ndim, tf.size(C)

(TensorShape([24]), 3, <tf.Tensor: shape=(), dtype=int32, numpy=24>)

In [37]:
tf.size(B)

<tf.Tensor: shape=(), dtype=int32, numpy=24>

In [38]:
tf.size(B).numpy()

24

In [39]:
A.shape[0]

24

In [40]:
B.shape[-1]

4

In [41]:
C.shape[1]

4

In [42]:
A1 = [1, 2, 3, 4, 5]
A1[:2]

[1, 2]

In [43]:
C1 = C[:2]
C1

<tf.Tensor: shape=(2, 4), dtype=int64, numpy=
array([[1, 2, 3, 4],
       [5, 6, 7, 8]])>

In [44]:
C2 = C[1:3, 2:3]
C2

<tf.Tensor: shape=(2, 1), dtype=int64, numpy=
array([[ 7],
       [11]])>

In [45]:
r2_tensor = tf.constant([[5, 6], [2, 3], [7, 9],
                         [15, 16], [12, 13], [17, 19]])
r2_tensor

<tf.Tensor: shape=(6, 2), dtype=int32, numpy=
array([[ 5,  6],
       [ 2,  3],
       [ 7,  9],
       [15, 16],
       [12, 13],
       [17, 19]], dtype=int32)>

In [46]:
r2_tensor[:, :1]

<tf.Tensor: shape=(6, 1), dtype=int32, numpy=
array([[ 5],
       [ 2],
       [ 7],
       [15],
       [12],
       [17]], dtype=int32)>

In [47]:
r2_tensor[:, -1]

<tf.Tensor: shape=(6,), dtype=int32, numpy=array([ 6,  3,  9, 16, 13, 19], dtype=int32)>

In [48]:
r3_tensor = r2_tensor[..., tf.newaxis]
r3_tensor

<tf.Tensor: shape=(6, 2, 1), dtype=int32, numpy=
array([[[ 5],
        [ 6]],

       [[ 2],
        [ 3]],

       [[ 7],
        [ 9]],

       [[15],
        [16]],

       [[12],
        [13]],

       [[17],
        [19]]], dtype=int32)>

In [49]:
tf.expand_dims(r3_tensor, axis=-1)

<tf.Tensor: shape=(6, 2, 1, 1), dtype=int32, numpy=
array([[[[ 5]],

        [[ 6]]],


       [[[ 2]],

        [[ 3]]],


       [[[ 7]],

        [[ 9]]],


       [[[15]],

        [[16]]],


       [[[12]],

        [[13]]],


       [[[17]],

        [[19]]]], dtype=int32)>

In [50]:
tf.expand_dims(r2_tensor, axis=0)

<tf.Tensor: shape=(1, 6, 2), dtype=int32, numpy=
array([[[ 5,  6],
        [ 2,  3],
        [ 7,  9],
        [15, 16],
        [12, 13],
        [17, 19]]], dtype=int32)>

In [54]:
exp_r2 = tf.expand_dims(r2_tensor, axis=1)
exp_r2

<tf.Tensor: shape=(6, 1, 2), dtype=int32, numpy=
array([[[ 5,  6]],

       [[ 2,  3]],

       [[ 7,  9]],

       [[15, 16]],

       [[12, 13]],

       [[17, 19]]], dtype=int32)>

In [52]:
r2_tensor.shape

TensorShape([6, 2])